link<-"https://www.imdb.com/search/title/?groups=top_250&sort=boxoffice_gross_us,desc" 
library(robotstxt) 
path<-paths_allowed(link)
library(rvest) 
web<-read_html(link) 
library(dplyr) 
num1<-web%>%html_nodes(".text-primary")%>%html_text()
name<-web%>%html_nodes(".lister-item-header a")%>%html_text()
runtime<-web%>%html_nodes(".runtime")%>%html_text()
rating<-web%>%html_nodes(".ratings-imdb-rating strong")%>%html_text()
gross<-web%>%html_nodes(".ghost~ .text-muted+ span")%>%html_text()
imdbgross<-data.frame(num1,name,runtime,rating,gross) 
View(imdbgross)
